// AVTOMATIK GENERATSIYA QILINGAN — QO'LDA TAHRIRLAMANG.
// Yangilash: node scripts/gen-api-permissions.mjs
//
// Har bir /api/* route'i uni ishlatadigan sahifalarga bog'langan. Xodim
// shu sahifalardan KAMIDA BITTASINI ko'ra olsa, route ochiq bo'ladi.
// Qo'lda beriladigan qarorlar (ommaviy route'lar va h.k.) skript ichida.

/** Sessiyasiz ochiq route'lar. */
export const PUBLIC_API: readonly string[] = [
  "/api/auth/login",
  "/api/auth/activate",
  "/api/auth/verify-token",
  "/api/auth/forgot-password",
  "/api/auth/reset-password",
  "/api/auth/resend-invite",
  "/api/auth/force-logout",
  "/api/auth/logout",
  "/api/sync/cron",
  "/api/telegram/webhook",
  "/api/telegram/student",
  "/api/student-web/me",
  "/api/health/ping",
  "/api/health/db",
];

/** Faqat shu HTTP metodlar uchun sessiyasiz ochiq. */
export const PUBLIC_API_METHODS: Record<string, readonly string[]> = {
  "/api/management-cv": ["POST"],
  "/api/sorovnoma": ["POST"],
};

/** Sessiya yetarli — qo'shimcha ruxsat talab qilinmaydi. */
export const SHARED_API: readonly string[] = [
  "/api/auth/change-password",
  "/api/auth/lock",
  "/api/auth/unlock",
  "/api/branch",
  "/api/gamification/activity",
  "/api/gamification/competition",
  "/api/gamification/excuse",
  "/api/gamification/homework",
  "/api/gamification/lesson",
  "/api/gamification/month-close",
  "/api/gamification/ranking",
  "/api/gamification/referral",
  "/api/gamification/shop",
  "/api/gamification/shop/eligible",
  "/api/gamification/shop/image",
  "/api/gamification/shop/items",
  "/api/gamification/shop/items/[id]",
  "/api/gamification/shop/orders",
  "/api/gamification/shop/orders/[id]/return",
  "/api/gamification/students",
  "/api/gamification/students/[id]",
  "/api/gamification/students/[id]/referral-leads",
  "/api/gamification/students/[id]/shop",
  "/api/gamification/students/[id]/transactions",
  "/api/gamification/transactions",
  "/api/gamification/transactions/[id]/cancel",
  "/api/gamification/transactions/[id]/cancel-preview",
  "/api/gamification/transactions/[id]/undo",
  "/api/home-stats",
  "/api/hr-employees/ref",
  "/api/notifications",
  "/api/people/directory",
  "/api/profile",
  "/api/pupils",
  "/api/search/students",
  "/api/sessions",
  "/api/sidebar-counts",
  "/api/sorovnoma",
  "/api/staff-tasks",
  "/api/staff-tasks/[id]",
  "/api/staff-tasks/[id]/file",
  "/api/staff-tasks/fines",
  "/api/staff-tasks/fines/[id]",
  "/api/staff-tasks/settings",
  "/api/staff-tasks/stats",
  "/api/staff-tasks/upload",
  "/api/tasks/inbox",
];

/** Route → kerakli ruxsatlar. Xodimda ULARDAN BITTASI bo'lsa yetarli. */
export const API_PERMISSIONS: Record<string, readonly string[]> = {
  "/api/attendance": ["/nazorat-davomat", "/nazorat-davomat-analytics", "/nazorat-missed-groups"],
  "/api/block-test-exams": ["/blok-testlar"],
  "/api/block-test-exams/[id]": ["/blok-testlar"],
  "/api/block-test-types": ["/blok-test-turlari", "/blok-testlar"],
  "/api/block-test-types/[id]": ["/blok-test-turlari"],
  "/api/bonuses": ["/finance-bonus", "/finance-cashflow", "/management-xodimlar"],
  "/api/bonuses/[id]": ["/finance-bonus"],
  "/api/branches": ["/management-filiallar", "/management-xodimlar", "/nazorat-branches", "/nazorat-feedback", "/offline-courses", "/orders-list", "/settings-academic", "/settings-app", "/settings-finance", "/settings-gamification", "/settings-general", "/settings-integrations", "/settings-management", "/settings-sales"],
  "/api/branches/[id]": ["/management-filiallar"],
  "/api/cashboxes": ["/finance-analytics", "/finance-bonus", "/finance-cash", "/finance-cashflow", "/finance-payroll", "/finance-penalty", "/finance-reports", "/finance-transactions", "/management-xodimlar"],
  "/api/cashboxes/[id]": ["/finance-cash"],
  "/api/cashboxes/[id]/adjust": ["/finance-cash"],
  "/api/cashboxes/[id]/set-primary": ["/finance-cash"],
  "/api/cashboxes/[id]/transfer": ["/finance-cash"],
  "/api/cashboxes/[id]/transfer-to": ["/finance-cash"],
  "/api/cashboxes/handover": ["/finance-cash"],
  "/api/contracts": ["/contract", "/students-list"],
  "/api/contracts/[id]": ["/contract"],
  "/api/edu-categories": ["/edu-category", "/imtihon", "/online-courses", "/orders-list", "/students-list"],
  "/api/edu-categories/[id]": ["/edu-category"],
  "/api/employee-salary-summary": ["/finance-cash"],
  "/api/employees": ["/management-xodimlar"],
  "/api/employees/[id]": ["/management-xodimlar"],
  "/api/employees/[id]/password": ["/management-xodimlar"],
  "/api/equipment": ["/groups-equipments", "/groups-rooms"],
  "/api/equipment/[id]": ["/groups-equipments"],
  "/api/feedback": ["/nazorat-feedback"],
  "/api/finance-contracts": ["/finance-fin-contract", "/finance-revenue-plan"],
  "/api/finance-contracts/[id]": ["/finance-fin-contract"],
  "/api/gamification/levels": ["/settings-academic", "/settings-app", "/settings-finance", "/settings-gamification", "/settings-general", "/settings-integrations", "/settings-management", "/settings-sales"],
  "/api/gamification/reasons": ["/settings-academic", "/settings-app", "/settings-finance", "/settings-gamification", "/settings-general", "/settings-integrations", "/settings-management", "/settings-sales"],
  "/api/gamification/reasons/[id]": ["/settings-academic", "/settings-app", "/settings-finance", "/settings-gamification", "/settings-general", "/settings-integrations", "/settings-management", "/settings-sales"],
  "/api/gamification/reasons/[id]/active": ["/settings-academic", "/settings-app", "/settings-finance", "/settings-gamification", "/settings-general", "/settings-integrations", "/settings-management", "/settings-sales"],
  "/api/gamification/settings": ["/settings-academic", "/settings-app", "/settings-finance", "/settings-gamification", "/settings-general", "/settings-integrations", "/settings-management", "/settings-sales"],
  "/api/gamification/shop/budget": ["/settings-academic", "/settings-app", "/settings-finance", "/settings-gamification", "/settings-general", "/settings-integrations", "/settings-management", "/settings-sales"],
  "/api/gamification/students/[id]/ledger": ["/students-list"],
  "/api/gender-guess": ["/management-xodimlar"],
  "/api/group-tasks": ["/groups-tasks"],
  "/api/group-tasks/[id]": ["/groups-tasks"],
  "/api/groups": ["/active-students", "/archive-students", "/blok-testlar", "/finance-cash", "/finance-fin-contract", "/first-lessons", "/groups", "/groups-schedule", "/groups-students", "/imtihon", "/management-xodimlar", "/nazorat-davomat", "/nazorat-davomat-analytics", "/nazorat-missed-groups", "/offline-courses", "/online-courses", "/orders-list", "/reports-rooms", "/reports-served", "/seasonal-assessment", "/students-list"],
  "/api/groups/[id]": ["/groups"],
  "/api/groups/[id]/attendance": ["/groups"],
  "/api/groups/[id]/attendance/history": ["/groups"],
  "/api/groups/[id]/lessons": ["/groups"],
  "/api/groups/[id]/notes": ["/groups"],
  "/api/groups/[id]/students": ["/first-lessons", "/groups", "/imtihon", "/new-students", "/orders-list", "/seasonal-assessment", "/students-list"],
  "/api/groups/[id]/tasks": ["/groups"],
  "/api/groups/import": ["/groups"],
  "/api/hr-employees": ["/blok-testlar", "/management-xodimlar"],
  "/api/hr-employees/[id]": ["/management-rollar", "/management-xodimlar"],
  "/api/hr-employees/[id]/notes": ["/management-xodimlar"],
  "/api/hr-employees/[id]/password": ["/management-xodimlar"],
  "/api/hr-employees/[id]/salary-ledger": ["/management-xodimlar"],
  "/api/hr-employees/[id]/students": ["/management-xodimlar"],
  "/api/hr-employees/import": ["/management-xodimlar"],
  "/api/imtihon/group": ["/imtihon"],
  "/api/imtihon/uzbmb": ["/imtihon"],
  "/api/imtihon/uzbmb/[id]": ["/imtihon"],
  "/api/lead-settings": ["/orders-list", "/settings-academic", "/settings-app", "/settings-finance", "/settings-gamification", "/settings-general", "/settings-integrations", "/settings-management", "/settings-sales"],
  "/api/legacy-entries": ["/students-list"],
  "/api/management-cv": ["/management-cv"],
  "/api/management-cv/[id]": ["/management-cv"],
  "/api/management-cv/[id]/file": ["/management-cv"],
  "/api/moderators": ["/finance-cash", "/finance-fin-contract", "/first-lessons", "/orders-list", "/parents", "/students-list"],
  "/api/news": ["/sales-news"],
  "/api/news/[id]": ["/sales-news"],
  "/api/offline-courses": ["/blok-test-turlari", "/groups", "/groups-schedule", "/imtihon", "/management-xodimlar", "/offline-courses", "/orders-list"],
  "/api/offline-courses/[id]": ["/blok-test-turlari", "/groups", "/groups-schedule", "/imtihon", "/management-xodimlar", "/offline-courses", "/orders-list"],
  "/api/offline-courses/[id]/levels": ["/blok-test-turlari", "/groups", "/groups-schedule", "/imtihon", "/management-xodimlar", "/offline-courses", "/orders-list"],
  "/api/offline-courses/[id]/levels/[levelId]": ["/blok-test-turlari", "/groups", "/groups-schedule", "/imtihon", "/management-xodimlar", "/offline-courses", "/orders-list"],
  "/api/offline-courses/[id]/lists": ["/blok-test-turlari", "/groups", "/groups-schedule", "/imtihon", "/management-xodimlar", "/offline-courses", "/orders-list"],
  "/api/offline-courses/import": ["/offline-courses"],
  "/api/online-courses": ["/online-courses"],
  "/api/online-courses/[id]": ["/online-courses"],
  "/api/online-courses/[id]/bind": ["/online-courses"],
  "/api/orders": ["/first-lessons", "/management-xodimlar", "/new-students", "/orders-list", "/reports-admins-perf", "/reports-funnel", "/reports-teachers-perf"],
  "/api/orders/[id]": ["/first-lessons", "/orders-list"],
  "/api/orders/[id]/comments": ["/orders-list"],
  "/api/orders/[id]/holat": ["/orders-list"],
  "/api/penalties": ["/finance-cashflow", "/finance-penalty", "/management-xodimlar"],
  "/api/penalties/[id]": ["/finance-penalty"],
  "/api/planned-expenses": ["/finance-planned"],
  "/api/planned-expenses/[id]": ["/finance-planned"],
  "/api/pupils/[id]": ["/students-list"],
  "/api/pupils/[id]/activity": ["/students-list"],
  "/api/pupils/[id]/password": ["/students-list"],
  "/api/pupils/[id]/status": ["/students-list"],
  "/api/reports/balance": ["/reports-balance"],
  "/api/reports/debtors": ["/reports-unpaid"],
  "/api/roles": ["/management-rollar", "/management-xodimlar"],
  "/api/roles/[id]": ["/management-rollar"],
  "/api/roles/coverage": ["/management-rollar"],
  "/api/rooms": ["/groups", "/groups-rooms", "/groups-schedule", "/reports-rooms"],
  "/api/rooms/[id]": ["/groups-rooms"],
  "/api/salary-runs": ["/finance-payroll"],
  "/api/salary-runs/[id]": ["/finance-payroll"],
  "/api/salary-runs/employees-payroll": ["/finance-cash", "/finance-payroll", "/management-xodimlar"],
  "/api/salary-runs/month-cashflow": ["/finance-payroll"],
  "/api/sales-plans": ["/sales-plan"],
  "/api/seasonal-assessments": ["/seasonal-assessment"],
  "/api/seasonal-assessments/[id]": ["/seasonal-assessment"],
  "/api/settings": ["/archive-students", "/first-lessons", "/management-xodimlar", "/nazorat-davomat", "/orders-list", "/settings-academic", "/settings-app", "/settings-finance", "/settings-gamification", "/settings-general", "/settings-integrations", "/settings-management", "/settings-sales", "/students-list"],
  "/api/settings-lists": ["/finance-analytics", "/finance-cash", "/finance-cashflow", "/finance-payroll", "/finance-reports", "/groups", "/management-xodimlar", "/orders-list", "/settings-academic", "/settings-app", "/settings-finance", "/settings-gamification", "/settings-general", "/settings-integrations", "/settings-management", "/settings-sales"],
  "/api/settings-lists/[id]": ["/settings-academic", "/settings-app", "/settings-finance", "/settings-gamification", "/settings-general", "/settings-integrations", "/settings-management", "/settings-sales"],
  "/api/sms-analytics": ["/nazorat-sms-analytics"],
  "/api/sms-messages": ["/archive-students", "/first-lessons", "/orders-list", "/sales-messages", "/students-list"],
  "/api/sms-templates": ["/archive-students", "/first-lessons", "/orders-list", "/sales-sms", "/students-list"],
  "/api/sms-templates/[id]": ["/sales-sms"],
  "/api/stories": ["/sales-stories"],
  "/api/stories/[id]": ["/sales-stories"],
  "/api/student-reports": ["/management-xodimlar", "/reports-cancelled", "/reports-cancelled-attend", "/reports-diff-payments", "/reports-discounts", "/reports-leave-reasons"],
  "/api/student-sources": ["/sales-sources"],
  "/api/student-sources/options": ["/imtihon", "/orders-list", "/sales-sources", "/students-list"],
  "/api/student-sources/options/manage": ["/sales-sources"],
  "/api/students/balances": ["/active-students", "/archive-students", "/expiring-subs", "/finance-cash", "/finance-fin-contract", "/groups", "/nazorat-davomat", "/new-students", "/parents", "/students-list"],
  "/api/support-analytics": ["/nazorat-support-analytics"],
  "/api/surveys": ["/sales-marketing"],
  "/api/surveys/[id]": ["/sales-marketing"],
  "/api/sync": ["/finance-sync"],
  "/api/task-types": ["/groups-tasks", "/students-list", "/tasks"],
  "/api/task-types/[id]": ["/groups-tasks", "/students-list", "/tasks"],
  "/api/tasks": ["/students-list"],
  "/api/tasks/[id]": ["/students-list"],
  "/api/teachers": ["/finance-cash", "/first-lessons", "/groups", "/imtihon", "/orders-list", "/reports-served"],
  "/api/temp-staff": ["/vaqtinchalik"],
  "/api/temp-staff/[id]": ["/vaqtinchalik"],
  "/api/temp-staff/invite": ["/vaqtinchalik"],
  "/api/transaction-entries": ["/finance-cash", "/finance-transactions", "/management-xodimlar", "/students-list"],
  "/api/transaction-entries/[id]/cancel": ["/finance-cash"],
  "/api/transaction-entries/[id]/pupil": ["/finance-transactions"],
  "/api/transaction-entries/[id]/transfer-confirm": ["/finance-cash"],
  "/api/transaction-entries/[id]/transfer-reject": ["/finance-cash"],
  "/api/transaction-entries/facets": ["/finance-cash", "/management-xodimlar"],
  "/api/transaction-entries/moderator-summary": ["/management-xodimlar"],
  "/api/transaction-entries/notes": ["/finance-cash"],
  "/api/transaction-entries/revenue-summary": ["/finance-revenue-plan"],
  "/api/transaction-entries/served-summary": ["/reports-served"],
  "/api/transaction-entries/students": ["/finance-transactions", "/management-xodimlar"],
  "/api/transaction-entries/unassigned": ["/finance-transactions"],
  "/api/transaction-types": ["/finance-analytics", "/finance-cash", "/finance-cashflow", "/finance-flow", "/finance-reports", "/finance-tx-types", "/management-xodimlar"],
  "/api/transaction-types/[id]": ["/finance-tx-types"],
  "/api/transactions": ["/finance-analytics"],
  "/api/transactions/summary": ["/finance-analytics", "/finance-cashflow", "/finance-flow", "/finance-pnl", "/finance-reports"],
  "/api/turnstile-io": ["/management-xodimlar", "/nazorat-davomat", "/nazorat-turnstile-io"],
  "/api/upload/image": ["/finance-penalty", "/management-xodimlar", "/online-courses", "/sales-stories", "/settings-academic", "/settings-app", "/settings-finance", "/settings-gamification", "/settings-general", "/settings-integrations", "/settings-management", "/settings-sales"],
  "/api/upload/video": ["/online-courses", "/sales-stories"],
  "/api/work-schedules": ["/management-ish-jadvali", "/management-xodimlar"],
  "/api/work-schedules/[id]": ["/management-ish-jadvali"],
};
